export const introObj = {
  'Pro Bono Offices': 'Pro Bono is generally used for free or low-cost professional legal services. In the US, all lawyers are suggested under ethical rules to contribute at least 50 hours to Pro Bono services in order to help those in need. Find nearby Pro Bono offices for affordable legal help.',
  'Unemployment Offices': 'If you have lost your job or been furloughed due to COVID-19 and severe economy, we will provide you with accurate and reliable information about unemployment assistance and benefits. Search Unemployment Offices by state, and get everything you need about the nearest office.',
  'Employment Departments': 'Want to find available job services and training? Need to file a claim for unemployment, disability, or paid family leave benefits? Or intend to manage your tax account and find important resources to succeed? Search Employment Departments on our site now, and you\'ll find the help you need.',
  'Victim Assistance Centers': 'Victim Assistance Centers are responsible for assisting and providing services via advocacy, education, and emotional support to all survivors of violence and crime in different areas. The mission of the organization is to bring hope and make changes for those people.',
  Courts: 'Courts are the main means to resolve disputes in legal systems. As a government institution, courts have the authority to adjudicate legal disputes between parties and implement the administration of justice in all matters in conformity to the law. All people have the right to bring their claims to court.',
  'Bar Associations': 'A bar association, also called a legal association, is a group of lawyers that are not only dealing with issues affecting the legal profession but also dedicated to serving their own members. Members involved in bar associations are qualified as barristers or advocates. For practicing attorneys, membership in bar associations may be mandatory or optional.',
  'District Attorney Offices': 'District Attorney Offices are representing the United States federal government in United States courts of appeals and United States district courts. The offices are responsible for bringing criminal charges against someone in a particular area or state.',
  'Departments of Justice': 'The Department of Justice, also called the Justice Department, was established to enforce the law and administrate justice in the United States. Formed in 1870, the department is led by the United States Attorney General, ensuring public safety against foreign and domestic threats.',
  'Attorney Generals': 'The attorney general is the main legal advisor to the government. In jurisdictions, attorney generals have executive responsibility for law enforcement, prosecutions or even legal affairs generally. In practice, the attorney general provides legal advice to the government that varies between jurisdictions.'
}
